FILL_WITH_MEAN = "fill with mean"
FILL_WITH_MEDIAN = "fill with median"
FILL_WITH_MODE = "fill with mode"
FILL_WITH_ZERO = "fill with zero"
FILL_WITH_CONSTANT = "fill with constant"
DROP_ROWS = "drop rows"
IGNORE = "ignore" 